package riscv_pkg;

    typedef enum logic [5:0] {
        INSTR_ADD,
        INSTR_SUB,
        INSTR_AND,
        INSTR_OR,
        INSTR_XOR,
        INSTR_SLL,
        INSTR_SRL,
        INSTR_SRA,
        INSTR_SLT,
        INSTR_SLTU,
        INSTR_ADDI,
        INSTR_ANDI,
        INSTR_ORI,
        INSTR_XORI,
        INSTR_SLLI,
        INSTR_SRLI,
        INSTR_SRAI,
        INSTR_SLTI,
        INSTR_SLTIU,
        INSTR_LW,
        INSTR_LH,
        INSTR_LHU,
        INSTR_LB,
        INSTR_LBU,
        INSTR_SW,
        INSTR_SH,
        INSTR_SB,
        INSTR_BEQ,
        INSTR_BNE,
        INSTR_BLT,
        INSTR_BGE,
        INSTR_BLTU,
        INSTR_BGEU,
        INSTR_JAL,
        INSTR_JALR,
        INSTR_LUI,
        INSTR_AUIPC,

        // extra garbage
        INSTR_CSRRW,
        INSTR_CSRRS,
        INSTR_CSRRC,
        INSTR_CSRRWI,
        INSTR_CSRRSI,
        INSTR_CSRRCI,
        INSTR_ECALL,
        INSTR_MRET,
        INSTR_FENCE,

        INSTR_UNKNOWN
    } instr_type;

endpackage